
version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:10.16

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "antirotor@users.noreply.github.com"
            git config --global user.name "Website Deployment Script"
            echo "machine github.com login antirotor password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=antirotor USE_SSH=false yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters:
            branches:
              only: master
